### ISSUE TITLE
The proposal name is wrong (we already have auto called packages)

### ISSUE THREAD

**Issue by roberth** [nixpkgs-architecture/simple-package-paths#10]
"auto called packages" is a bad name because
 - auto-calling is the technical term for what the old Nix CLI does, not something Nixpkgs does
 - automatic callPackage invocations are just an implementation detail of what we're trying to achieve

The removal of the categories is a far more significant change than the ability to remove a trivial list of callPackage calls.
We could have 95% of the benefits of the RFC without doing readDir (and having a sorted list of files in a .nix file somewhere, causing non-zero but very few merge conflicts).

How about: Simple package paths

**Comment by infinisil** [comment]
I think this sounds reasonable, would like to hear what others think though

**Comment by infinisil** [comment]
(Ultimately this doesn't matter much if at all though)

**Comment by roberth** [comment]
* Remove the package directory hierarchy
* Seize the means of location
* A intersectional approach against package discrimination
* Smash the entropy

Ok, got a bit carried away.
