### ISSUE TITLE
Explain what `unit` is

### ISSUE THREAD

**Issue by infinisil** [nixpkgs-architecture/simple-package-paths#16]
The current draft uses `pkgs/unit/<name>/pkg-fun.nix` as the directory structure. We should explain what "unit" is and why that name is fitting.

We decided on this name among other candidates [in the last meeting](https://discourse.nixos.org/t/2022-11-14-nixpkgs-architecture-team-meeting-17/23172/2#directory-root-4).

[On discourse](https://discourse.nixos.org/t/2022-11-14-nixpkgs-architecture-team-meeting-17/23172/3?u=infinisil), @blaggacao points out that [std](https://github.com/divnix/std)'s "cell" concept is the same as the "unit" we're talking about here.

Also on Discourse I proposed this general description of a "unit" in nixpkgs:

> A collection of standardized files related to the same software component

**Comment by blaggacao** [comment]
> A standardized collection of functionality related to the same software component

( "files" &rarr; "functionality")


In the context of nixpkgs, a Collection of (Nix) Packages, the "software component", in a sense that goes actually beyond a "package", is the _domain_ around which related functionality accrues.
