### ISSUE TITLE
Where to move extra package files?

### ISSUE THREAD

**Issue by infinisil** [nixpkgs-architecture/simple-package-paths#19]
The `hello` packages directory contains both a `default.nix` file and a `test.nix` file. The `default.nix` file should be moved to `pkgs/unit/hell/hello/pkg-fun.nix`, but where should the `test.nix` file go?

If we want a standardized structure in these unit directories, we can't put it in `pkgs/unit/hell/hello/test.nix` since that clobbers the namespace. We also don't want to define a standard `test.nix` file just yet (though a cool idea). There's also many other types of files used, like patch files, which might make sense to put under a `patches` directory, but that's also not something this RFC should be bothered with.

I think we need to decide on a conventional directory name for unstructured extra files, such that we can move all such extra files in an automated way under e.g. `pkgs/unit/hell/hello/unstructured/test.nix`. Here's some proposals:
- `extra`
- `files`
- `legacy` (indicating that this is inherited from the old structure)
- `misc`

**Comment by roberth** [comment]
We'll have a rename tool so any clobbering will be easy to fix.

```bash
for file in pkgs/unit/*/test.nix; do
  hypothetical-nix-tool rename-paths --in . --from $file --to $(dirname $file)/test/test.nix;
done
```

**Comment by infinisil** [comment]
We discussed this [in yesterdays NAT meeting](https://discourse.nixos.org/t/2022-11-28-nixpkgs-architecture-team-meeting-19/23572#pkgsunithellhellounstructuredtestnix-7).

The conclusion we reached was that we could just put these files next to the `pkg-fun.nix` file, because:
- For now it's only a nixpkgs-internal convention, so we can easily change this later and we don't have to make any third-party compatibility guarantees
- Currently we're only concerned with packages and nothing else, we can change this once more is involved
